### ISSUE TITLE
Batch upload

### ISSUE THREAD

**Issue by iamsoum** [Jerry23011/VirusTotal-macOS#8] opened 2024-11-03 06:48 UTC
**Is your feature request related to a problem? Please describe.**
Problem is there's no batch upload!

**Describe the solution you'd like**
Batch upload, ofcourse!

**Describe alternatives you've considered**
Banging my head against the wall.

**Additional context**
No.

**Comment by Jerry23011** [comment] 2024-11-03 06:50
Duplicate of #7

**Closed as not planned by Jerry23011** 2024-11-03 06:50 UTC
Labels: duplicate, enhancement
