### ISSUE TITLE
Not working for files without extension and UI bug

### ISSUE THREAD

**Issue by tanu360** [Jerry23011/VirusTotal-macOS#2] opened 2024-06-09 05:25 UTC
It is not working for .app inside paths. i.e : /System/Applications/Font Book.app/Contents/MacOS/Font Book

![CleanShot 2024-06-09 at 10 50 02@2x](https://github.com/Jerry23011/VirusTotal-macOS/assets/33043201/5864c326-6cbd-467f-952c-320fe6646d7e)

Suggestion : I think the problem is in "File Extension" handling. It should scan those files which does not have extension as well. currently It is not scanning file which does not have any extension.

Font Book - Not working
Font book.abc / Font book.html / Font Book.exe - Working

There is a bug in UI as well where the score value is not placed properly within the circle. 

![CleanShot 2024-06-09 at 10 54 19@2x](https://github.com/Jerry23011/VirusTotal-macOS/assets/33043201/e73584cc-5f2b-4084-914c-66fb6bd9cdd3)

Overall this app is great.

**Comment by Jerry23011** [comment] 2024-06-09 05:59
Thanks a lot for the feedback.

I think you’re right on the issue for file extension handling, which is something I didn’t consider.

About the UI, I think it’s an issue with the view’s minimum height. I’ll look into those later

**Comment by Jerry23011** [comment] 2024-06-09 07:53
@tanu360 does the UI bug appear every time? How did you reproduce it?

**Comment by tanu1337** [comment] 2024-06-09 09:01
> @tanu360 does the UI bug appear every time? How did you reproduce it?

I created a foldet named tanu-priv-project
Inside that I out index.html

Drag and Drop that html into the software.
Then the software started scanning and result appeared like this.

**Comment by Jerry23011** [comment] 2024-06-09 09:06
Did you try resizing the window vertically? I want to make sure if it’s the min height issue

**Comment by tanu1337** [comment] 2024-06-09 09:12
Currently I tried different file from different locations.
I also tried resizing and opening in full screen yet the UI is same like the screenshot.

I am using M3 Chip.

**Comment by Jerry23011** [comment] 2024-06-09 09:28
May I know your screen size (or Mac model)and if you’re using any scaling options in System Settings -> Display?

**Comment by tanu1337** [comment] 2024-06-09 09:43
> May I know your screen size (or Mac model)and if you’re using any scaling options in System Settings -> Display?

MacBook Pro M3
Everything is set to default. No extra changes.

**Comment by Jerry23011** [comment] 2024-06-09 10:49
Can you try this one and see if it solves the extension handling issue?
[VirusTotal-Debug.zip](https://github.com/user-attachments/files/15751557/VirusTotal-Debug.zip)

**Comment by tanu360** [comment] 2024-06-09 12:26
Yes files without any extension can be scanned but It can not scan .app means dummy.app can not be scanned possibly it is considering that as a folder but not a file while on the other hand official Virustotal can do it.

![CleanShot 2024-06-09 at 17 52 52@2x](https://github.com/Jerry23011/VirusTotal-macOS/assets/33043201/e1066a35-2e83-4b9f-8f94-b3ffaa346e8d)

1. Full Screen mode yet the UI is overlapping at the result.
2. Support for .app 
3. The speed I don't know why it is slow. File got uploaded, it just keep spinning for 3-5 minutes yet no result appears but when I click on the button "View on VirusTotal" and open the web url and let it finish their either in 5-10 seconds then as soon as it finished in the web url then the app shows result. If I don't open the web url then it just keep spinning and spinning.

**Comment by Jerry23011** [comment] 2024-06-09 12:40
> Full Screen mode yet the UI is overlapping at the result.

I can't reproduce that on my Mac yet, may I know your system version?
> Support for .app

How VT website handles this is to archive `.app` into a `.zip`. Since `.app` or `.playground` are all directories and handled automatically, I have no plans to support uploading .app directly. One way is to archive it yourself and drop it in.
> The speed I don't know why it is slow.

This is something I have very little control on. If you use a web debugging proxy, you'll see that VT actually returns 400 status code with the requests but the analysis data are empty. The app has to wait for VT to return a successful result (which could take up to several minutes)

The app should give you results within 10 seconds the analysis is actually done. I'm pretty confident that you don't have to open the website to trigger the results in the app

**Comment by tanu360** [comment] 2024-06-09 12:46
1. My system is latest one with sonoma.
2. Oh thanks I will just scan .app by making it to .zip
3. I will debug the network and cross check if all is fine. 

Thank you.

**Comment by Jerry23011** [comment] 2024-06-09 12:48
The UI thing is super strange, we seem to have different spacings for some items in the form. I'll check the code later

edit: we have the exact same screen size & pixel per inch according to Apple's tech specs
<img width="900" alt="local" src="https://github.com/Jerry23011/VirusTotal-macOS/assets/89069957/dc5b7dc5-b5fb-4942-a8b6-bc8776153770">
<img width="900" alt="2" src="https://github.com/Jerry23011/VirusTotal-macOS/assets/89069957/39923901-25ca-4b89-bf57-748cfd37db24">

**Comment by Jerry23011** [comment] 2024-06-09 12:54
Can you reproduce the same issue in URL Analysis, even if you couldn't could you send me a screenshot of the report for google.com?

**Comment by tanu360** [comment] 2024-06-09 12:56
For URL 👍

<img width="1180" alt="image" src="https://github.com/Jerry23011/VirusTotal-macOS/assets/33043201/3ffa089a-894f-4804-a601-78d1ec34848d">

For File :

<img width="1180" alt="image" src="https://github.com/Jerry23011/VirusTotal-macOS/assets/33043201/6786a08b-6de6-48c0-8f7b-04259c7547e7">


looks like for URL, It is working fine but for File not.

Regarding the speed, you are right.
File extension : Solved
.app scanning : make Zip and then upload
UI in URL scanning : Good already 


**UI in file scanning : only needs to be fixed.**

Model Name:	MacBook Pro
Model Identifier:	Mac15.3
System Firmware Version:	10151.121.1
OS Loader Version:	10151.121.1
Display:

<img width="716" alt="image" src="https://github.com/Jerry23011/VirusTotal-macOS/assets/33043201/5cfaa531-7c2d-4a1e-8173-924c72f3c2d5">

Up to Date:

<img width="716" alt="image" src="https://github.com/Jerry23011/VirusTotal-macOS/assets/33043201/0c5b1cef-e1f2-48de-ac11-9f23d551eb55">

**Comment by Jerry23011** [comment] 2024-06-09 14:32
I setup a completely new virtual machine and installed macOS 14.5. The view seems to be fine. I also looked closely at the SwiftUI view in your Settings.app. The cells in Form is also larger than the normal ones vertically.

I think it has something to do with your global settings that's affecting this particular component of SwiftUI but I don't know what it is

<img width="839" alt="Screenshot 2024-06-09 at 7 27 35 AM" src="https://github.com/Jerry23011/VirusTotal-macOS/assets/89069957/38a5cfb2-7fee-4f2a-99ec-924565a7a995">

**Comment by tanu360** [comment] 2024-06-09 14:55
I will test it on my other MacBooks and then let you know.

**Comment by tanu360** [comment] 2024-06-12 12:43
Please update the latest release with new commits.

**Comment by Jerry23011** [comment] 2024-06-12 13:04
Yeah sure

**Comment by Jerry23011** [comment] 2024-06-12 13:04
> Please update the latest release with new commits.

How did it go, does it work on other Macs?

**Comment by tanu360** [comment] 2024-06-12 13:08
> > Please update the latest release with new commits.
> 
> How did it go, does it work on other Macs?

I tried in Macbook Air and macbook Pro, in both the Ui is same.
I will try in older intel soon.

**Comment by Jerry23011** [comment] 2024-06-12 13:24
>I tried in Macbook Air and macbook Pro, in both the Ui is same.
I will try in older intel soon.

Closing this issue for now, please file a new issue to track the UI problem

**Closed as completed by Jerry23011** 2024-06-12 13:24 UTC
Labels: bug
